(require 'load-packages)
(load-packages)
(unless (package-installed-p 'inf-ruby)
  (print "install inf-ruby")
  (package-install 'inf-ruby)
)
(unless (package-installed-p 'ruby-electric)
  (print "install ruby-electric")
  (package-install 'ruby-electric)
)
