(require 'load-packages)
(load-packages)

(unless (package-installed-p 'evil)
  (print "install evil")
  (package-install 'evil))

(if (> emacs-major-version 23)
  (unless (package-installed-p 'flycheck)
    (print "install flycheck")
    (package-install 'flycheck))
  (unless (package-installed-p 'flymake-ruby)
    (print "install flymake-ruby")
    (package-install 'flymake-ruby))
  (unless (package-installed-p 'flymake-cursor)
    (print "install flymake-cursor")
    (package-install 'flymake-cursor))
)
